spring:
  application:
    name: springboot_mybatis_crud
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    mode: HTML5
    cache: false
    suffix: .html
    encoding: UTF-8
    prefix: classpath:templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml
---
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://codedot.co.kr:3306/test_user_01?characterEncoding=UTF-8
    username: test_user_01
    password: dl945pa